name = "wafrs"
main = "src/index.ts"
compatibility_date = "2023-02-14"
route = "waf.rs/*"
node_compat = true

kv_namespaces = [
    { binding = "wafrs", id = "ae0ed606ec2544859474a2fe6e97aebc", preview_id = "ae0ed606ec2544859474a2fe6e97aebc" }
]

[site]
bucket = "./public"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "wafrs-db"
database_id = "1576301c-f4d9-482a-9c72-1a641027cf9e"
